// EEPROM Locations
#define VERSION_START 0
#define VERSION_LENGTH 8

#define DEVICE_NAME_START 8
#define DEVICE_NAME_LENGTH 32

#define DEVICE_TYPE_START 40
#define DEVICE_TYPE_LENGTH 2

#define WIFI_SSID_START 42
#define WIFI_SSID_LENGTH 32

#define WIFI_PASS_START 74
#define WIFI_PASS_LENGTH 32

#define SERVER_URL_START 106
#define SERVER_URL_LENGTH 32

#define SERVER_USERNAME_START 138
#define SERVER_USERNAME_LENGTH 32

#define SERVER_PASSWORD_START 170
#define SERVER_PASSWORD_LENGTH 32

#define CRC_START 254
#define CRC_LENGTH 2
